// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZi9LOpW_A2yqJLQ8PB154093g0fcdQaM',
    appId: '1:728610286777:web:36173601d7538202583f68',
    messagingSenderId: '728610286777',
    projectId: 'recipieapp-19dfe',
    authDomain: 'recipieapp-19dfe.firebaseapp.com',
    storageBucket: 'recipieapp-19dfe.appspot.com',
    measurementId: 'G-RYKLJ6SYXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz-4ePI2AOxB6k_EWntpgMexj0kbq0Rr8',
    appId: '1:728610286777:android:e64375b60071c449583f68',
    messagingSenderId: '728610286777',
    projectId: 'recipieapp-19dfe',
    storageBucket: 'recipieapp-19dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEygwJYDh7e3r14f47pO6-7wlmeZtVvtg',
    appId: '1:728610286777:ios:131ce341b988a5b9583f68',
    messagingSenderId: '728610286777',
    projectId: 'recipieapp-19dfe',
    storageBucket: 'recipieapp-19dfe.appspot.com',
    iosBundleId: 'com.example.recipieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEygwJYDh7e3r14f47pO6-7wlmeZtVvtg',
    appId: '1:728610286777:ios:131ce341b988a5b9583f68',
    messagingSenderId: '728610286777',
    projectId: 'recipieapp-19dfe',
    storageBucket: 'recipieapp-19dfe.appspot.com',
    iosBundleId: 'com.example.recipieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZi9LOpW_A2yqJLQ8PB154093g0fcdQaM',
    appId: '1:728610286777:web:9984c39cc4d22d59583f68',
    messagingSenderId: '728610286777',
    projectId: 'recipieapp-19dfe',
    authDomain: 'recipieapp-19dfe.firebaseapp.com',
    storageBucket: 'recipieapp-19dfe.appspot.com',
    measurementId: 'G-1MLNN61VNM',
  );
}
